db-uri = "postgres://authenticator:authenticatorpassword@localhost:5432/herobase"
db-schema = "public"
db-anon-role = "anon"
server-port = 3000
jwt-secret = "herobase-secret-key-at-least-32-characters-long"
